name: Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  check-repository-freshness:
    runs-on: ubuntu-latest
    steps:
      - name: Compare latest time and set variables
        run: |
          LATEST_TIME=$(curl -s https://api.github.com/repos/misakaio/chnroutes2/commits/master | jq -r '.commit.committer.date')
          LOCAL_TIME=$(curl -s https://api.github.com/repos/${{ github.repository }}/commits/master | jq -r '.commit.committer.date')
          if [ "$LATEST_TIME" != "$LOCAL_TIME" ]; then
            echo "NeedToSync=true" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Checkout codebase
        uses: actions/checkout@v4
        if: ${{ env.NeedToSync }}

      - name: Install dependencies
        if: ${{ env.NeedToSync }}
        run: |
          python -m pip install --upgrade pip
          pip install requests
          

      - name: Modify chnroutes.txt
        if: ${{ env.NeedToSync }}
        run: |
          python modify_chnroutes.py
      
      - name: Commit and push
        if: ${{ env.NeedToSync }}
        run: |
          git config --global user.name 'GitHub Bot'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update chnroutes.txt"
          git push

          
